name: pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/brewfourtytwo/mml:latest
            ghcr.io/brewfourtytwo/mml:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" > ./envfile
      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: mml
          file: docker-stack.yaml
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          env_file: ./envfile